module.exports = {
  boxShadow: {
    generic: 'none',
  },
  borderRadius: {
    sm: '4px',
  },
  colors: {
    primary: {
      main: '#08A4DA',
      light: '#5eed53',
      hover: '#0790bf',
    },
    brand: {
      main: '#051B35',
      light: '#051B35',
      text: '#051B35',
    },
    secondary: {
      main: '#334C6C',
      hover: '#2c425f',
      light: '#778CA6',
    },
    danger: {
      main: '#F44336',
    },
    success: {
      main: '#5CB660',
    },
    info: '#52ADF5',
    warning: '#EF9A1D',
    footer: {
      bottomText: '#778CA6',
    },
    body: '#ECF0F3',
    lightSpacer: 'rgba(119,140,166,0.15)',
  },
  spacing: {
    bodyPadding: 25,
    bodyPaddingMedium: 20,
    bodyPaddingSmall: 20,
    footerMainTopPadding: 1.5,
    footerMainBottomPadding: 0,
    footerPrePadding: 0,
    settingsBodyPadding: '30px 15px',
    settingsMarginTop: 0,
  },
  buttons: {
    borderRadius: 3,
    fontSize: 16,
    color: '#FFF',
    primaryBgColor: '#08A4DA',
    primaryBgHoverColor: '#0790bf',
    primaryColor: '#fff',
    secondaryBgColor: '#334C6C',
    secondaryBgHoverColor: '#2c425f',
    secondaryColor: '#fff',
    transform: 'uppercase',
    disabled: {
      backgroundColor: '#0794C5',
      color: 'rgba(255,255,255, 0.5)',
    },
  },
  fonts: {
    family: 'Roboto',
    weight: {
      bold: 700,
    },
    size: {
      lg: '18px',
      md: '16',
    },
  },
  header: {
    backgroundMobile: 'linear-gradient(180deg,#051b35 0%,#053451 100%)',
    navHeightMobile: 0,
    navFontSize: 16,
    needsHamburger: true,
  },
  footer: {
    listColor: '#fff',
    listTitleWeight: 700,
    timerBgColor: '#213956',
    iconsBg: '#213956',
    subFooterHeight: 60,
    clockIconSize: 18,
    clockIconMargin: '0 6px',
    bgColor: '#051B35',
    color: '#fff',
  },
  communicationPrefs: {
    items: {
      backgroundColor: '#ffffff',
      border: '1px solid rgba(119,140,166,0.15)',
    },
  },
  pageContainer: {
    smallMaxWidth: 480,
    backgroundColor: '#ECF0F3',
  },
  pageInnerContainer: {
    boxShadow: '0px 2px 4px rgba(5, 27, 53, 0.1)',
    titleWeight: 700,
  },
  login: {
    bgImgTop: '/assets/images/container-bg-img.webp',
    linkDecoration: 'none',
    linkColor: '#08A4DA',
    linkFontSize: 16,
    buttonFullWidth: true,
  },
  registration: {
    width: 520,
    left: '0',
    borderRadius: 4,
    boxShadow: '0px 4px 4px rgba(5, 27, 53, 0.1)',
    bgImg: '/assets/images/container-bg-img.webp',
    titleWeight: 700,
    blockTitleWeight: 700,
    blockTitleTransform: 'uppercase',
    blockTitleBorder: '1px solid #E6ECF1',
    blockTitleColor: '#778CA6',
    blockTitleFontSize: 12,
    blockTitlePaddingBottom: 8,
  },
  inputs: {
    border: '1px solid #9DB4C8',
    borderRadius: 4,
    padding: '10px 13px',
    fontSize: 16,
    height: 48,
    backgroundColor: '#ffff',
    color: '#051B35',
    labelLeft: 20,
    labelTop: 15,
    labelActiveFontSize: 12,
    labelActiveTop: -8,
    labelActiveLeft: 10,
    labelBackgroundColor: '#fff',
    labelPadding: 4,
    marginBottom: 18,
    selectPadding: '10px 13px',
    disabled: {
      border: 'none',
      backgroundColor: '#E6ECF1',
      color: '#778CA6',
    },
    active: {
      borderColor: '#08A4DA',
    },
  },
  customFileInput: {
    backgroundColor: '#E6ECF1',
    labelColor: '#051B35',
    buttonFontColor: '#FFF',
    buttonFontWeight: 700,
    buttonFontSize: '15px',
    buttonColor: '#334C6C',
    border: 'none',
  },
  toggleCheck: {
    slider: {
      width: '18px',
      height: '18px',
      left: '4px',
      checkedLeft: '55%',
      boxShadow: 'none',
    },
    height: '24px',
    minWidth: '48px',
    backgroundColor: '#778CA6',
    checkedBgColor: '#08A4DA',
  },
  helpBlock: {
    titleWeight: 700,
    titleColor: '#778CA6',
    padding: '0',
    color: '#051B35',
    blockTitleWeight: 700,
    blockTitleColor: '#051B35',
    iconSize: 20,
  },
  userMenu: {
    boxShadow: '0px 4px 4px rgba(5, 27, 53, 0.1)',
    borderRadius: 4,
    itemBorder: '1px solid rgba(119, 140, 166, 0.15)',
    itemWeight: 700,
    itemTransform: 'uppercase',
    itemFontSize: 14,
    itemHeight: 48,
    width: 330,
    backgroundColor: '#fff',
    subItemBgColor: '#fff',
    itemIconColor: '#778CA6',
  },
  settingsMenu: {
    fontSize: 14,
    color: '#051B35',
    borderRadius: 4,
    activeBgColor: '#E6ECF1',
    fontWeight: 700,
    fontTransform: 'uppercase',
    subBackgroundColor: '#fff',
    iconColor: '#778CA6',
  },
  inputContainer: {
    backgroundColor: '#fff',
    borderRadius: 0,
    padding: 25,
    fullWidthButton: true,
    iconButton: false,
    customInput: true,
    inputHeight: 68,
    inputBgColor: '#E6ECF1',
    inputFontSize: 24,
    inputFontWeight: 700,
    inputAlign: 'center',
    quickBorderRadius: 4,
    quickPadding: '10px 0',
    quickColor: '#fff',
    quickFontWeight: 700,
    quickBorder: 'none',
    quickBg: '#334C6C',
  },
  paymentMethods: {
    inRow: 4,
    padding: '25px 20%',
    mobilePadding: '30px 5px',
    textAlign: 'left',
    border: '1px solid #E6ECF1',
    borderRadius: 4,
    activeOutline: '0px 0px 0px 3px #051B35',
  },
  settingsPage: {
    titleFontWeight: 700,
    titleMargin: '0 0 15px 0',
    subTextMargin: '0 0 16px 0',
    containerMaxWidth: 1150,
  },
  dateFilter: {
    padding: '0',
    margin: '0',
    periodBgColor: '#E6ECF1',
    periodColor: '#051B35',
    periodActiveColor: '#fff',
    periodBorderRadius: 4,
    dateInputBg: '#E6ECF1',
    dateInputBorder: '#E6ECF1',
    borderColor: 'none',
  },
  table: {
    headerFontSize: 12,
    headerColor: '#778CA6',
    itemColor: '#051B35',
    itemFontSize: 14,
    itemBorder: '1px solid #E6ECF1',
  },
  questionsContainer: {
    borderRadius: 4,
    bgColor: '#fff',
    titleFontWeight: 700,
    itemBorder: '1px solid #E6ECF1',
  },
  infoContainer: {
    bgColor: '#fff',
    color: '#051B35',
    boldColor: '#051B35',
    borderRadius: 4,
    borderTop: '1px solid rgba(119, 140, 166, 0.15)',
    titleMargin: '0',
    limitNumberColor: '#051B35',
    limitNumberFontSize: 18,
    limitNumberFontWeight: 700,
    limitInfoColor: '#778CA6',
    limitInfoTitleWeight: 700,
    limitInfoTitleTransform: 'uppercase',
    limitInfoBorder: '1px solid rgba(119, 140, 166, 0.15)',
  },
  alert: {
    color: '#051B35',
    padding: '16px 16px',
    iconColor: '#FFF',
    fontSize: 16,
    iconSize: 16,
    iconBgSize: 20,
    margin: '15px 0 !important',
    invertedIconBg: false,
    transparentBg: true,
  },
  promotions: {
    cardPadding: '24px',
  },
  modals: {
    color: '#051B35',
    title: {
      fontWeight: 700,
      fontSize: '24px',
    },
  },
  genericModalWidth: '505px',
  bonuses: {
    containerBgColor: '#fff',
    subTextColor: '#476387',
    boxShadow: '0px 0px 4px rgb(5 27 53 / 18%)',
    barColor: '#778CA6',
    barBgColor: '#ECF0F3',
    editHoverBgColor: '#ECF0F3',
    labelBgColor: '#E6ECF1',
  },
};
