module.exports = {
  boxShadow: {
    generic: 'rgb(0 0 0 / 12%) 0px 0px 5px 0px',
  },
  borderRadius: {
    sm: '8px',
  },
  colors: {
    primary: {
      main: '#44d9e6',
      light: '#5eed53',
      hover: '#1ab6c3',
    },
    brand: {
      main: '#000',
      light: '#000',
      text: '#031442',
    },
    secondary: {
      main: '#666666',
    },
    footer: {
      bottomText: 'rgba(255,255,255,0.75)',
    },
    body: '#fafafa',
  },
  spacing: {
    bodyPadding: 80,
    bodyPaddingMedium: 45,
    bodyPaddingSmall: 20,
    footerMainTopPadding: 3,
    footerMainBottomPadding: 1.5,
    settingsBodyPadding: '0 25px 0 0',
    settingsMarginTop: 50,
  },
  buttons: {
    borderRadius: 16,
    fontSize: 13,
    primaryBgColor: '#44d9e6',
    primaryBgHoverColor: '#1dcfdf',
    primaryColor: '#031442',
  },
  fonts: {
    family: 'Dax offc',
    weight: {
      bold: 500,
    },
    size: {
      lg: '16px',
    },
  },
  footer: {
    listColor: 'rgba(255, 255, 255, 0.75)',
    listTitleWeight: 500,
    subFooterHeight: 80,
    clockIconSize: 35,
    clockIzonMargin: '0',
  },
  communicationPrefs: {
    items: {
      backgroundColor: '#f9f9f9',
      border: '1px solid rgb(229, 229, 229)',
    },
  },
  pageContainer: {
    backgroundColor: '#ECF0F3',
  },
  pageInnerContainer: {
    titleWeight: 400,
  },
  login: {
    formBorderBottom: '1px solid #e5e5e5',
  },
  registration: {
    width: 630,
    borderRadius: 10,
    boxShadow: '0 0 5px 0 rgb(0 0 0 / 12%)',
    blockTitleWeight: 500,
    blockTitleFontSize: 16,
    titleWeight: 400,
  },
  inputs: {
    border: '1px solid #cccccc',
    borderRadius: 4,
    padding: '17px 0.75rem 0.375rem 0.75rem',
    fontSize: 15,
    height: 38,
    backgroundColor: '#f9f9f9',
    color: '#4c4c4c',
    labelLeft: 12,
    labelTop: 12,
    labelActiveFontSize: 9,
    labelActiveTop: 4,
    labelActiveLeft: 12,
    labelBackgroundColor: 'transparent',
    labelPadding: 0,
    marginBottom: 8,
    selectPadding: '0 5px',
    disabled: {
      backgroundColor: '#e5e5e5',
      border: '1px solid #cccccc',
      color: '#4c4c4c',
    },
    invalid: {
      backgroundColor: '#fef5f5',
    },
  },
  customFileInput: {
    backgroundColor: '#f9f9f9',
    labelColor: '#4c4c4c',
    buttonFontColor: '#4c4c4c',
    buttonFontWeight: 400,
    buttonFontSize: '16px',
    buttonColor: '#ccc',
    border: '1px solid #cccccc',
  },
  toggleCheck: {
    slider: {
      width: '20px',
      height: '20px',
      left: '5px',
      checkedLeft: '60%',
      boxShadow: 'rgb(0 0 0 / 30%) 0px 2px 4px 0px',
    },
    height: '32px',
    minWidth: '62px',
    backgroundColor: 'rgb(229, 229, 229)',
    checkedBgColor: 'rgb(68, 217, 230)',
  },
  helpBlock: {
    titleWeight: 500,
    titleColor: '#202020',
    padding: '12px 16px 0 16px',
    border: '1px solid #dfdfdf',
    color: '#202020',
    blockTitleWeight: 500,
    iconSize: 36,
  },
  userMenu: {
    boxShadow: '0 -2px 20px 0 rgb(0 0 0 / 30%)',
    borderRadius: 8,
    itemBorder: '1px solid #e5e5e5',
    itemWeight: 400,
    itemHeight: 64,
    itemFontSize: 16,
    width: 330,
    backgroundColor: '#fafafa',
    subItemBgColor: '#efeff4',
  },
  settingsMenu: {
    fontSize: 16,
    color: 'rgba(3, 20, 66, 0.7)',
    fullHeight: true,
    subItemBorder: '1px solid #e5e5e5',
    subBackgroundColor: 'rgb(239, 239, 244)',
  },
  inputContainer: {
    backgroundColor: '#efeff4',
    padding: 15,
    iconButton: true,
    borderRadius: 8,
    inputHeight: 38,
    quickBoxShadow: '0 2px 10px 0 rgb(0 0 0 / 20%)',
    quickBorderRadius: 8,
    quickPadding: '23px 0',
    quickColor: '#051B35',
    quickFontWeight: 500,
    quickBorder: 'none',
    quickBg: '#fff',
  },
  paymentMethods: {
    inRow: 6,
    padding: '15px',
    textAlign: 'center',
    boxShadow: '0 2px 10px 0 rgb(0 0 0 / 20%)',
    borderRadius: 8,
    activeOutline: '0px 0px 0px 3px #000',
  },
  settingsPage: {
    titleFontWeight: 500,
    titleMargin: '0',
    subTextMargin: '0 0 24px 0',
  },
  dateFilter: {
    padding: '20px 22px',
    margin: '0 0 1.5rem 0',
    periodBgColor: '#fff',
    periodColor: 'rgba(0,0,0,0.8)',
    periodActiveColor: 'rgba(0,0,0,0.8)',
    periodBorderRadius: 8,
    dateInputBg: '#fff',
    dateInputBorder: '1px solid #e0e0e0',
    borderColor: '#44d9e6',
  },
  table: {
    headerFontSize: 12,
    headerColor: '#202020',
    itemColor: '#202020',
    itemFontSize: 11,
    itemBorder: '1px solid #cccccc',
  },
  questionsContainer: {
    borderRadius: 8,
    titleFontWeight: 500,
    border: '1px solid #cccccc',
    itemBorder: '1px solid #cccccc',
  },
  infoContainer: {
    bgColor: '#cff3e1',
    color: '#999999',
    boldColor: '#000000',
    borderRadius: 8,
    border: '1px solid #cccccc',
    titleMargin: '0 0 8px 0',
    limitNumberColor: '#44d9e6',
    limitNumberFontSize: 14,
    limitNumberFontWeight: 500,
    limitInfoColor: '#051B35',
    limitInfoTitleWeight: 500,
  },
  alert: {
    color: '#4c4c4c',
    padding: '20px 15px',
    iconColor: '#fff',
    fontSize: 14,
    iconSize: 24,
    iconBgSize: 32,
    transparentBg: true,
  },
  promotions: {},
  modals: {
    color: '#323232',
    title: {
      fontWeight: 500,
      fontSize: '1.375rem',
    },
  },
  genericModalWidth: '680px',
};
